#!/usr/bin/env python3
"""Score yourself on the labelled dev set. Run this constantly.

    python scripts/evaluate_dev.py                     # run the agent, then score
    python scripts/evaluate_dev.py --traces dev_traces.jsonl   # score an existing run
    python scripts/evaluate_dev.py --category refund_large --show 20
    python scripts/evaluate_dev.py --retrieval-only    # retrieval quality alone, no LLM

The dev set is 24 queries over the same 12 categories as the 72-query test set,
generated by the same script. It is a thermometer, not the exam: 2 queries per
category, so treat a one-category swing as noise and read the overall number and
the per-category shape.
"""
import argparse
import json
import sys
from pathlib import Path

sys.path.insert(0, str(Path(__file__).resolve().parent.parent))

from evalkit import metrics  # noqa: E402
from support_agent import trace  # noqa: E402
from support_agent.agent import SupportAgent  # noqa: E402

ROOT = Path(__file__).resolve().parent.parent
DEV_Q = ROOT / "data" / "dev_queries.jsonl"
DEV_G = ROOT / "data" / "dev_gold.jsonl"
TRACKER = ROOT / "comparison_tracker.md"


def _extract_tracker_baseline():
    """Read the saved baseline values from comparison_tracker.md if present."""
    if not TRACKER.exists():
        return {}
    text = TRACKER.read_text(encoding="utf-8")
    baseline = {}
    for line in text.splitlines():
        if not line.startswith("|") or "Before" in line or "---" in line:
            continue
        parts = [p.strip() for p in line.strip("|").split("|")]
        if len(parts) < 4:
            continue
        metric = parts[0]
        if metric in {"Metric", "system_score", "route", "actions", "facts", "citations"}:
            try:
                baseline[metric] = float(parts[1])
            except ValueError:
                pass
    return baseline


def update_tracker(report):
    """Refresh the markdown tracker with the newest evaluation numbers."""
    if not TRACKER.exists():
        return
    baseline = _extract_tracker_baseline()
    current = {
        "system_score": report["system_score"],
        "route": report["components"]["route"],
        "actions": report["components"]["actions"],
        "facts": report["components"]["facts"],
        "citations": report["components"]["citations"],
    }
    lines = [
        "# Before vs After Comparison Tracker",
        "",
        "Use this file to record your baseline and then update it after each improvement.",
        "",
        "## Baseline from current report.json",
        "",
        "| Metric | Before | After | Delta |",
        "|---|---:|---:|---:|",
    ]
    for metric in ["system_score", "route", "actions", "facts", "citations"]:
        before = baseline.get(metric, current[metric])
        after = current[metric]
        delta = after - before
        lines.append(f"| {metric} | {before} | {after} | {delta:+.4f} |")
    lines.extend([
        "",
        "## How to update it",
        "",
        "1. Run the evaluation:",
        "   ```bash",
        "   python scripts/evaluate_dev.py --json report.json",
        "   ```",
        "2. Copy the new values from `report.json` into the `After` column.",
        "3. Calculate delta as:",
        "   ```text",
        "   after - before",
        "   ```",
        "4. Keep one row per milestone or change set.",
        "",
        "## Notes",
        "",
        "- This is the easiest way to track whether a change actually improved the agent.",
        "- Keep the baseline values unchanged until you intentionally start a new milestone.",
        "- Use the same command after every major code change.",
    ])
    TRACKER.write_text("\n".join(lines) + "\n", encoding="utf-8")


def retrieval_only(queries, golds):
    """Recall@k of the gold citation documents — no generation, no cost."""
    from support_agent.retrieval import get_retriever
    r = get_retriever()
    gold_by_id = {g["query_id"]: g for g in golds}
    hits = total = 0
    per_cat = {}
    for q in queries:
        want = set(gold_by_id[q["query_id"]].get("citations") or [])
        if not want:
            continue
        got = {h.doc_id for h in r.search(q["query"])}
        found = len(want & got)
        hits += found
        total += len(want)
        cat = q["category"]
        a, b = per_cat.get(cat, (0, 0))
        per_cat[cat] = (a + found, b + len(want))
    print(f"retrieval recall@{r.top_k} (mode={r.mode}): {hits}/{total} = {hits / max(total, 1):.3f}\n")
    for cat, (a, b) in sorted(per_cat.items(), key=lambda kv: kv[1][0] / max(kv[1][1], 1)):
        print(f"  {cat:<24} {a:>3}/{b:<3} {a / max(b, 1):.2f}")


def main():
    ap = argparse.ArgumentParser()
    ap.add_argument("--traces", default=None, help="score an existing traces file")
    ap.add_argument("--out", default=str(ROOT / "dev_traces.jsonl"))
    ap.add_argument("--limit", type=int, default=0)
    ap.add_argument("--workers", type=int, default=4)
    ap.add_argument("--category", default=None, help="only this category")
    ap.add_argument("--show", type=int, default=8, help="print the N worst queries")
    ap.add_argument("--json", default=None, help="also write the full report here")
    ap.add_argument("--retrieval-only", action="store_true")
    a = ap.parse_args()

    queries = trace.read_jsonl(DEV_Q)
    golds = trace.read_jsonl(DEV_G)
    if a.category:
        queries = [q for q in queries if q["category"] == a.category]
        golds = [g for g in golds if g["category"] == a.category]
    if a.limit:
        queries, golds = queries[:a.limit], golds[:a.limit]

    if a.retrieval_only:
        retrieval_only(queries, golds)
        return

    if a.traces:
        preds = trace.read_jsonl(a.traces)
    else:
        from concurrent.futures import ThreadPoolExecutor
        agent = SupportAgent()
        with ThreadPoolExecutor(max_workers=max(1, a.workers)) as pool:
            preds = list(pool.map(agent.resolve, queries))
        for p in preds:
            p.pop("_debug", None)
        trace.write_jsonl(a.out, preds)
        print(f"wrote {len(preds)} traces -> {a.out}\n")

    report = metrics.score_all(preds, golds)
    print(metrics.format_report(report, show_rows=a.show))
    if a.json:
        Path(a.json).write_text(json.dumps(report, indent=2))
        print(f"\nfull report -> {a.json}")
    update_tracker(report)


if __name__ == "__main__":
    main()
